### ISSUE TITLE
FYI: Webpack 2.1.0-beta.23 introduces new API

### ISSUE THREAD

**Issue by kevinSuttle** [pascalduez/postcss-apply#17]
https://github.com/webpack/webpack/issues/3018#issuecomment-248187254

**Comment by pascalduez** [comment]
Hi,

interesting, but how is that related to the `postcss-apply` plugin?

**Comment by kevinSuttle** [comment]
IIRC, the plugin API will have to change.

**Comment by pascalduez** [comment]
The Webpack plugin API, not PostCSS one nor plugins.

**Comment by kevinSuttle** [comment]
Ah ok. Thanks. Just wanted to throw a heads up.
