### ISSUE TITLE
Any reason for choosing Unlicense over MIT?

### ISSUE THREAD

**Issue by paazmaya** [pascalduez/postcss-apply#18]
I am just wondering what might be the reason of choosing Unlicense, in favour for example MIT (used by PostCSS itself https://github.com/postcss/postcss/blob/master/LICENSE).

MIT would be clearer in the lawyers eyes, and even if the license would need to be changed later in to something else, the versions published with MIT are still valid as MIT.
This would not seem to be the case with Unlicense.

**Comment by pascalduez** [comment]
Hi,

are you in some sort of crusade against the Unlicence? ;)

I like the Unlicence for small projects where nothing is "invented" like plugins are. 
I like the concept of the public domain.
It's just simple and straightforward. 
[But that would explain it better](http://unlicense.org/#why-use-the-unlicense).

**Comment by paazmaya** [comment]
Not on a crusade, just trying to make everyone happy.

Thank you for the answer.
