### ISSUE TITLE
Remove comments by default?

### ISSUE THREAD

**Issue by dbox** [pascalduez/postcss-apply#20]
Forgive me if this has already been discussed. Wondering if postcss-apply should remove comments by default? I know that this is the job of a minifier, but it doesn't seem helpful to have the comments if none of their respective rules show up.

![image](https://cloud.githubusercontent.com/assets/296130/22312170/66634d1a-e31c-11e6-884c-4b93446f75cb.png)

I'm working on a particularly large library of mixins, so maybe I'm fringe use-case.

Thoughts?

**Comment by pascalduez** [comment]
Hi,

makes sense I guess, will look into it.

**Comment by dbox** [comment]
@pascalduez thanks! Here to help with testing if you need.

**Comment by pascalduez** [comment]
`postcss-apply@0.10.0`
