### ISSUE TITLE
Console log in 0.6.0 version

### ISSUE THREAD

**Issue by iamfrntdv** [pascalduez/postcss-apply#25]
I have just updated plugin, and there is some console.log that outputs rules.

I have found it in ./dist/visitor.js:60

didn't find it in source code, so couldn't create pull request.. May be it already has been deleted, but the plugin wasn't published to npm

**Comment by pascalduez** [comment]
Uh! thanks for the report, will make a new release.

**Comment by pascalduez** [comment]
Should be fixed as of `postcss-apply@0.6.1` .
