### ISSUE TITLE
@apply is becoming available in Chrome

### ISSUE THREAD

**Issue by dotnetCarpenter** [pascalduez/postcss-apply#5]
> As of this writing (April 8, 2016), the feature is very new and has not yet landed in Google Chrome or even Chrome Canary, but it is available behind a flag in the latest Chromium nightly.
> http://zeke.sikelianos.com/css-from-the-future/

Perhaps it is time to re-phrase the README and check that `postcss-apply` follow the spec.
> Toying around an interesting idea, not really a spec yet ?

Ohh, just found your comment in https://github.com/MoOx/postcss-cssnext/issues/203#issuecomment-208735885

**Comment by pascalduez** [comment]
Hi,

`postcss-apply` follow the "spec" as much as possible from its very first version, and will stay on that path. But once again, I think it's not really a spec yet.

Anyway, I'll rephrase that sentence, it's not really appealing.

**Comment by JayGeorge** [comment]
Yes, please please stay on the draft spec path!

**Comment by dotnetCarpenter** [comment]
@pascalduez very good to know. I'm considering adding `postcss-apply` to our front end pipe line and knowing that this might be a standard is very appealing.
