### ISSUE TITLE
Is there some way to assign !important to a declaration block at apply-time?

### ISSUE THREAD

**Issue by wc-matteo** [pascalduez/postcss-apply#6]
e.g. `@apply --foo !important;`

Would it go against "the spec"?

**Comment by JayGeorge** [comment]
I’d be very surprised if this worked because Applys can have multiple properties. You would have to set the important declarations _within_ the foo apply itself.

**Comment by wc-matteo** [comment]
@JayGeorge Yes, I meant that calling `@apply` with `important` would set it for all properties.

The proplem with setting `important` within the declaration block is that if you need the same properties without it, you have to duplicate all of them. I know is not a general use case.

**Comment by JayGeorge** [comment]
Hm, well effectively setting `!important` on all the all the properties would be a bit of a sledgehammer approach.

I would suggest increasing the specificity of the class that you’re calling the apply to e.g.

```
body .some-class {
  @apply --foo;
};
```

I’m not involved in the spec but I would be surprised if they made it possible to add !important to Applies.

**Comment by wc-matteo** [comment]
In this case, being a style inclued in a (possibly) hostile environment, I need the (relative) security afforded by `imporant`.
