### ISSUE TITLE
How to use with webpack?

### ISSUE THREAD

**Issue by chimon2000** [pascalduez/postcss-apply#9]
I am attempting to use this feature in webpack, but I cannot figure out how to inject custom properties. This is fairly easy to do for var

````
        let variables = {
            'primary-toolbar': '#415464',
            'secondary-toolbar': "#488fb4"
        }
            require("postcss-cssnext")({
                features: {
                    customProperties: {
                        variables: variables,
                        'conversation-progress': `
                            {
                                margin: 0 auto;
                                position: fixed;
                                top: 50%;
                                left: 50%;
                            };
                        `
                    },
                    applyRule: {
                    }
                }
            })
````

However when attempting to do something similar for apply I get the `no custom properties set declared` error.

**Comment by pascalduez** [comment]
Hi,

this has nothing to do with webpack, it's just that there's no mechanism implemented to create custom property sets from js/config.

**Comment by chimon2000** [comment]
That's what I assumed, thanks for the clarification.  Since I'm using angular2, my use case isn't as simple as just plugging everything into one file.  As a workaround, I'm using [postcss-inject](https://github.com/admdh/postcss-inject) to inject `:root` into my components' css.

**Comment by kevinSuttle** [comment]
@chimon2000: See https://github.com/postcss/postcss-custom-properties/issues/32#issuecomment-237363712

**Comment by pascalduez** [comment]
Refs #15
